version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd src/handlers/hello-world && npm install
      - cd ../../..
      
  pre_build:
    commands:
      - echo Running tests...
      - cd src/handlers/hello-world && npm test
      - cd ../../..
      
  build:
    commands:
      - echo Building application...
      - cd src/handlers/hello-world
      - zip -r ../../../hello-world.zip .
      - cd ../../..
      
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - template.yaml
    - hello-world.zip
  name: serverless-app-$(date +%Y-%m-%d)
