AWSTemplateFormatVersion: '2010-09-09'
Description: 'CI/CD Pipeline for Serverless Application'

Parameters:
  GitHubRepo:
    Type: String
    Default: 'your-username/serverless-deployment-project'
  GitHubBranch:
    Type: String
    Default: 'main'

Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-artifacts-${AWS::AccountId}'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                  - cloudformation:*
                  - iam:*
                  - lambda:*
                  - apigateway:*
                Resource: '*'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-build'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 14
            pre_build:
              commands:
                - echo Installing SAM CLI
                - pip install aws-sam-cli
            build:
              commands:
                - echo Build started on `date`
                - sam build
            post_build:
              commands:
                - echo Build completed on `date`
          artifacts:
            files:
              - '**/*'
