AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Web Application - Deployment Pipeline

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  # DynamoDB Table
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-app-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # Lambda Function
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-hello-world"
      CodeUri: ../src/handlers/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref AppTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref AppApi

  # API Gateway
  AppApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Environment}-app-api"
      StageName: !Ref Environment

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
  
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref HelloWorldFunction
    
  TableName:
    Description: "DynamoDB Table Name"
    Value: !Ref AppTable
